### ISSUE TITLE
Develop a NodeJS script to combine all data files

### ISSUE THREAD

**Issue by curran** [earthrise-media/story-ukraine-grain#5]

**Comment by ejfox** [comment]
Started this here: https://github.com/earthrise-media/story-ukraine-grain/blob/295f61833ba89df91be44f92f1a3de54fb978238/scripts/clean_data.mjs

It re-uses the logic from our [Observable Notebook](https://observablehq.com/d/4b2c4cb1a680f45d) - the only thing missing is to combine into a single .csv instead of making a bunch of different .csvs

**Comment by ejfox** [comment]
Gonna close this since we have our script now
